version: "3.8"

services:
  backend:
    container_name: backend_container
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=rental_db
      - DB_PORT=3306
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - backend

  db:
    container_name: db_container
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rental_db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
